### ISSUE TITLE
No particles for the campfire ? (1.14)

### ISSUE THREAD

**Issue by SkyMinecraft01** [FaithfulX32/Faithful#30]
Hello,

Why doesn't the campfire have any particles? Is it a problem with your texture pack or a problem coming from me?

I have your texture pack "[1.14-s3](https://www.patreon.com/posts/faithful-1-14-s3-24069324)"

Thank you,
Aleyxandre

![2019-01-23_14 53 52](https://user-images.githubusercontent.com/29005043/51611168-df755780-1f1e-11e9-81a4-c38140668e7e.png)

**Comment by xMrVizzy** [comment]
Yeah, I know, I already made this texture, they will be added in the next update!
